# -*- coding: utf-8 -*-
"""Desafio agrupando dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gxo6wL_RS9CLejj_GvYGF2BwCKPk9zrz

Desafio 1: Como estão divididas as vendas das lojas de departamentos na Região Centro-Oeste nos anos de 2017 e 2018? O mesmo estado permaneceu como o que mais vendeu nesta região?

Desafio 2: Analisando cada departamento, como estão divididos os modos de envio em cada um deles percentualmente?
"""

#importação de bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#seleção de cores a ser utilizadas nos gráficos
AZUL1, AZUL2, AZUL3, AZUL4,AZUL5 = '#042033','#2C526B', '#567C96', '#90AEC2', '#D0E0EB'
CINZA1, CINZA2, CINZA3, CINZA4, CINZA5 = '#212529', '#495057', '#adb5bd', '#dee2e6', '#f8f9fa'
VERMELHO1, LARANJA1, AMARELO1, VERDE1, VERDE2 = '#e76f51', '#f4a261',	'#e9c46a', '#4c956c', '#2a9d8f'

#importação dos dados
dados = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/dataviz-graficos/master/dados/relatorio_vendas.csv')
dados.head(50)



dados.info()

#transformação dos tipos de dados para datetime
dados['data_pedido'] = pd.to_datetime(dados['data_pedido'], format='%Y-%m-%d')
dados['data_envio'] = pd.to_datetime(dados['data_envio'], format='%Y-%m-%d')

#criação de colunas em anos
dados['ano_pedido'] = dados['data_pedido'].dt.year
dados['ano_envio'] = dados['data_envio'].dt.year
dados.info()

dados_centro_oeste = dados.copy()

#Selecionando os dados desejados por região e anos(Centro-Oeste, 2017 e 2018)
dados_centro_oeste = dados.query('regiao == "Centro-Oeste" & (ano_pedido >= 2017 & ano_pedido <=2018)')


dados_centro_oeste

#agrupamento dos dados por anos, estado e somando as vendas de cada estado
vendas_centro_oeste = dados_centro_oeste.groupby(['ano_pedido', 'estado'])['vendas'].agg('sum')

vendas_centro_oeste

#Utilizando crosstab para categorizar em anos e Estados
vendas_centro_oeste = pd.crosstab(dados_centro_oeste['ano_pedido'], dados_centro_oeste['estado'], values=dados_centro_oeste['vendas'], aggfunc='sum')

vendas_centro_oeste

#Criação do nosso gráfico em barras empilhadas do Centro - Oeste
def grafico_barras_centro_oeste():
#definindo as cores padrão do nosso gráfico
  cores = [AZUL2,AZUL3,AZUL4,AZUL5]

#plotando o nosso grafico de barras empilhadas
  ax = vendas_centro_oeste.plot(kind='bar',stacked=True, figsize=(10,6), color= cores)

#formatando o layout do graficos
  ax.set_title('Vendas por Estado e Ano', loc= 'left', fontsize= 18, color= CINZA1)
  ax.set_xlabel('')
  ax.set_ylabel('')
  ax.set_yticklabels([])
  ax.xaxis.set_tick_params(labelsize = 14, rotation = 0)
  ax.set_frame_on(False)

#criação da legenda
  ax.legend(bbox_to_anchor = (1,1), reverse = True, title = 'Estados', title_fontsize = 12)

#Colocando os valores no gráfico e centralizando nas colunas
  for container in ax.containers:
    labels = [f'R${valor.get_height()/1000:,.0f}k'.replace(',', '.') for valor in container]
    ax.bar_label(container, labels=labels, label_type='center', fontsize=10, color = CINZA5)

  #Criação do texto no gráfico
  ax.text(1.34,1.0, 'Nos anos de $\\bf{2017}$ $\\bf{e}$ $\\bf{2018:}$\n'
  'O Estado que mais vendeu\n'
  'no $\\bf{Centro-Oeste}$ \n'
  'Foi o $\\bf{Distrito}$ $\\bf{Federal}$', fontsize= 14, linespacing= 1.45, color = AZUL1)
  return ax
ax = grafico_barras_centro_oeste()



"""Desafio 2: Analisando cada departamento, como estão divididos os modos de envio em cada um deles percentualmente?"""

#variavel departamentos
df_departamentos = dados.copy()
df_departamentos

#ajuntando os departamento e o modo de envio e somando as vendas
df_departamentos.groupby(['departamento', 'modo_envio'])['vendas'].agg('sum')

#Categorizando o numeros de vezes que a colunas departamento e modo de envio aparece em % e valores absolutos
teste = pd.crosstab(index = df_departamentos.modo_envio, columns=df_departamentos.departamento,normalize='index')
teste1 = pd.crosstab(index = df_departamentos.modo_envio, columns=df_departamentos.departamento)
teste1

teste

#plotando o gráfico em subplots(mais de um gráfico de uma área)
fig, axs = plt.subplots(1,2, figsize=(15,6),sharey=True)

#variaveis importantes para dizer onde estará dispostos os valores
left_automotivo = teste['Automotivo']
left_materiais = teste['Automotivo'] + teste['Materiais de construção']

left_automotivo1 = teste1['Automotivo']
left_materiais1 = teste1['Automotivo'] + teste1['Materiais de construção']

#criação do primeiro gráfico
axs[0].barh(teste.index, teste['Automotivo'], label='Automotivo', color=AZUL2)
axs[0].barh(teste.index, teste['Materiais de construção'], left=left_automotivo, label='Materiais de construção', color=AZUL3)
axs[0].barh(teste.index, teste['Jardinagem e paisagismo'], left=left_materiais, label='Jardinagem e paisagismo', color=AZUL4)

#formatando o layout do gráfico 1
axs[0].set_xlabel('')
axs[0].set_ylabel('')
axs[0].set_xticks([])
axs[0].yaxis.set_tick_params(labelsize=12)
axs[0].set_frame_on(False)

#definindo o titulo da figura dos dois gráficos
fig.suptitle('Divisão Percentual dos Modos de Envio por Departamento', fontsize=18, ha='center', color=CINZA1)

#Valores que vão conter em % no gráfico
for container in axs[0].containers:
    labels = [f'{valor.get_width()*100:.1f}%' for valor in container]
    axs[0].bar_label(container, label_type='center', labels=labels, fontsize=14, color=CINZA5)

#Definindo o tipo do segundo gráfico
axs[1].barh(teste1.index, teste1['Automotivo'], color=AZUL2)
axs[1].barh(teste1.index, teste1['Materiais de construção'], left=left_automotivo1, color=AZUL3)
axs[1].barh(teste1.index, teste1['Jardinagem e paisagismo'], left = left_materiais1, color=AZUL4)

#formatando o layout do 2 gráfico
axs[1].set_xlabel('')
axs[1].set_ylabel('')
axs[1].set_xticks([])
axs[1].yaxis.set_tick_params(labelsize=12)
axs[1].set_frame_on(False)
axs[0].legend(title='Departamentos', bbox_to_anchor=(1, 1))


#textos que estarão contidos em valores absolutos
for container in axs[1].containers:
    labels = [str(valor.get_width()) if valor.get_width()>100 else '' for valor in container]
    axs[1].bar_label(container, label_type='center', labels=labels, fontsize=8, color=CINZA5)
plt.tight_layout()


fig.show()

